### ISSUE TITLE
決めといたほうがよさそうなこと

### ISSUE THREAD

**Issue by hokaccha** [tan-yuki/mahjong-rules#1]
- 九種倒牌で親流れるか
- 二家和はダブロン or 上家
- 三家和は流れる or トリロン or 上家
- 二家和で三家和でダブロン、トリロンの場合のリーチ棒や本場の扱い
- 四風子連打は親流れるか
- 人和の役満 or 倍満 or 満貫
- チョンボは親流れるか
- 誤ロン、誤ツモはチョンボか（誤ロンはあがり放棄というところもある）
- 誤ポン、誤チー、誤カンのペナルティ
- パオはあり？あるなら具体的な役も。
- 自分のツモがないときに鳴けるか
- 4人リーチ 流れ or 続行
- 流し満貫は流局扱い or 和り扱い
- 自分が鳴いたりリーチしていても流し満貫成立するか
- カン4つで流局？
- 大明槓責任払い（http://www10.plala.or.jp/rascalhp/mjall.htm#c5-18）
- 国士無双の暗槓あがりアリorナシ
- 国士無双13面待ちのときのフリテン（http://www10.plala.or.jp/rascalhp/mjall.htm#c4-12）
- 明槓の場合にカンドラをめくるタイミング（http://www10.plala.or.jp/rascalhp/mjall.htm#c5-16）
- 多牌・勝敗時のペナルティ
- オーラス親がトップ目で流局したときに親がテンパイ宣言した場合にやめることができるか
- 鳴きの優先順位（ポン優先 or 発声優先）
- 修復不可能なぐらい山を壊したときのペナルティ
- 役満ご祝儀
- 数え役満でもご祝儀？
- 自分のツモがない場合にリーチできるか

**Comment by 1000ch** [comment]
基本的に競技ルールに賛成で、以下それに準ずるとすると

### 連荘と流局

> - 九種倒牌で親流れるか
> - 四風子連打は親流れるか
> - 4人リーチ 流れ or 続行
> - カン4つで流局？

流局・親の連チャンのようです。但し、四槓子の場合は流局せずカン不可能で続行、雀頭の完成を以って役満とあります。

### 誤ロン・誤ツモ・誤ポン・誤チー・誤カン

正規の和了が優先される。

> - 誤ロン、誤ツモはチョンボか（誤ロンはあがり放棄というところもある）
> - 誤ポン、誤チー、誤カンのペナルティ

**誤ポン、誤チー、誤カン** はチョンボ（牌を倒してしまうまでの行為）
**空ポン、空チー、空カン** はアガリ放棄（発声後に取りやめたりする行為）

### パオ

> - パオはあり？あるなら具体的な役も。

大三元（三種類目の三元牌）・大四喜（四種類目の三元牌）・四槓子（三槓子完成者に生牌をカンさせる）の3つに適用される。

**Comment by hokaccha** [comment]
> 流局・親の連チャンのようです。但し、四槓子の場合は流局せずカン不可能で続行、雀頭の完成を以って役満とあります。

これはよさそう

> 誤ポン、誤チー、誤カン はチョンボ（牌を倒してしまうまでの行為）
> 空ポン、空チー、空カン はアガリ放棄（発声後に取りやめたりする行為）

これは厳しいので供託1000点罰符ぐらいでいいと思うけどどうかな？

> 大三元（三種類目の三元牌）・大四喜（四種類目の三元牌）・四槓子（三槓子完成者に生牌をカンさせる）の3つに適用される。

これもよさそう

**Comment by 1000ch** [comment]
> これは厳しいので供託1000点罰符ぐらいでいいと思うけどどうかな？

:+1:

**Comment by tan-yuki** [comment]
@hokaccha @1000ch 
多分全部書いたんでみといてください
