### ISSUE TITLE
多牌が判明したとき、その次点で流れる or アガリ放棄で継続か

### ISSUE THREAD

**Issue by hiloki** [tan-yuki/mahjong-rules#10]
誤ロン・誤ツモは流れるとおもうけど、多牌ってどっちだろ。
経験上は罰符+アガリ放棄。

**Comment by tan-yuki** [comment]
https://github.com/tolymer/mahjong-rules#チョンボとするもの

現在チョンボ扱いです。他家から指摘があった時点でチョンボ。
理由としては、手に隠してイカサマし易いからだった気がします。

参考）http://www9.plala.or.jp/majan/chonbo04.html

**Comment by hiloki** [comment]
そうそう、チョンボ・罰符は良いんだけど、その時の局はどうなるんだろうなぁっていう。
流れるのか、続行なのか。

**Comment by hokaccha** [comment]
基本的にはチョンボの場合は原因に関係なく局は終了だろうなあ。

ただ多牌をチョンボにするかどうかは議論してもよさそう。チョンボにする基本的な理由は

> 理由としては、手に隠してイカサマし易いからだった気がします。

これだと思うけど信頼できる仲間内であれば少牌と同様にアガリ放棄でもいいという判断もありそう。
