### ISSUE TITLE
喰い替えの記載

### ISSUE THREAD

**Issue by hiloki** [tan-yuki/mahjong-rules#11]
喰い替えも色々あるということで、一応issue
http://majandofu.com/changing-formation

**Comment by tan-yuki** [comment]
まぁ、認めないってだけで罰則は特に必要ないかなと思うのですがどうでしょう

**Comment by hiloki** [comment]
罰則はいらないかとおもうんだけど、基本ルールに明記しとくものかどうかっていう。

**Comment by 1000ch** [comment]
フリーだとアガリ放棄で局は続行なケースもあります
